name             "slave-ci"
maintainer       "National Theatre"
maintainer_email "jdrawneek@nationaltheatre.org.uk"
license          "All rights reserved"
description      "Installs/Configures slave-ci"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.11"
depends          "webserver-dev-chef", ">= 0.0.1"
depends          "maven", ">= 0.0.1"
depends          "java", ">= 0.0.1"
depends          "nodejs", ">= 0.0.1"
depends          "mysql", ">= 0.0.1"
depends          "mysql-chef_gem", ">= 0.0.1"
depends          "database", ">= 0.0.1"
depends          "apache2", ">= 0.0.1"
