maintainer       "National Theatre"
maintainer_email "jdrawneek@nationaltheatre.org.uk"
license          "All rights reserved"
description      "Installs/Configures slave-ci"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.2"
depends          "webserver-dev-chef", ">= 0.0.1"
depends          "maven", ">= 0.0.1"
depends          "java", ">= 0.0.1"
depends          "nodejs", ">= 0.0.1"